# Generated by Django 3.2.7 on 2023-06-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposition',
            name='position',
            field=models.CharField(max_length=127, verbose_name='Позиция'),
        ),
    ]
